/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SearchParamsIndexImport } from './routes/searchParams/index'
import { Route as CatsIndexImport } from './routes/cats/index'
import { Route as CatsInfiniteImport } from './routes/cats/infinite'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchParamsIndexRoute = SearchParamsIndexImport.update({
  path: '/searchParams/',
  getParentRoute: () => rootRoute,
} as any)

const CatsIndexRoute = CatsIndexImport.update({
  path: '/cats/',
  getParentRoute: () => rootRoute,
} as any)

const CatsInfiniteRoute = CatsInfiniteImport.update({
  path: '/cats/infinite',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cats/infinite': {
      preLoaderRoute: typeof CatsInfiniteImport
      parentRoute: typeof rootRoute
    }
    '/cats/': {
      preLoaderRoute: typeof CatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/searchParams/': {
      preLoaderRoute: typeof SearchParamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CatsInfiniteRoute,
  CatsIndexRoute,
  SearchParamsIndexRoute,
])

/* prettier-ignore-end */
